// Generated by builder.py -- do not edit manually
// Run: python3 builder.py --implant ../oxide/target/debug/oxide-implant --psk oxide-lab-psk --salt <hex>
pub static ENCRYPTED_IMPLANT: &[u8] = &[];
